"""phase 3: event timestamps use clock_timestamp

Revision ID: 182cea8a4fac
Revises: f3c4d779f835
Create Date: 2026-09-09 17:10:44.911134+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (autogenerate emits halfvec columns)
import sqlalchemy as sa
from alembic import op

revision: str = "182cea8a4fac"
down_revision: str | None = "f3c4d779f835"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `now()` is the transaction start time, so a save and a dismiss recorded in
    # one request share a timestamp and their order is undefined — which made
    # "currently saved" return dismissed postings. An event log needs the
    # instant each event happened.
    op.alter_column(
        "user_job_events",
        "created_at",
        server_default=sa.text("clock_timestamp()"),
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_user_job_events_user_posting",
        "user_job_events",
        ["user_id", "posting_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column(
        "user_job_events",
        "created_at",
        server_default=sa.text("now()"),
        existing_type=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_job_events_user_posting", table_name="user_job_events")
    # ### end Alembic commands ###
