"""user score weights (phase 6 personalisation)

Revision ID: 69741dd4c4fc
Revises: ddb09d40b226
Create Date: 2026-09-12 09:53:07.406761+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (autogenerate emits halfvec columns)
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "69741dd4c4fc"
down_revision: str | None = "ddb09d40b226"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_score_weights",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("coefficients", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("adjustments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("events_used", sa.Integer(), nullable=False),
        sa.Column("ndcg_default", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("ndcg_personalised", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("rejected_reason", sa.Text(), nullable=True),
        sa.Column(
            "trained_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_score_weights")
    # ### end Alembic commands ###
