"""Phase 1 — per-requirement sentence vectors (§7.2)

Revision ID: 8507d0510fea
Revises: e68d36ca838f
Create Date: 2026-09-09 11:56:08.975707+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "8507d0510fea"
down_revision: str | None = "e68d36ca838f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_requirements", sa.Column("model", sa.Text(), nullable=True))
    op.add_column(
        "job_requirements",
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=384), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_requirements", "embedding")
    op.drop_column("job_requirements", "model")
    # ### end Alembic commands ###
