"""Initial schema — §6 of docs/PROJECT_PLAN.md

Revision ID: bd890a7822e8
Revises:
Create Date: 2026-09-08 17:25:31.491268+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "bd890a7822e8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions first: citext for case-insensitive email, pgcrypto for
    # gen_random_uuid(), vector for the halfvec column and its HNSW index,
    # pg_trgm for the company-alias review queries.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("actor", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("domain", sa.Text(), nullable=True),
        sa.Column("hq_country", sa.Text(), nullable=True),
        sa.Column("size_bucket", sa.Text(), nullable=True),
        sa.Column("careers_url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
    )
    op.create_table(
        "job_groups",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("canonical_posting_id", sa.UUID(), nullable=True),
        sa.Column("cluster_key", sa.Text(), nullable=False),
        sa.Column("member_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_sources",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("adapter", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("robots_ok", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("rate_limit_rpm", sa.Integer(), server_default=sa.text("20"), nullable=False),
        sa.Column("tier", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("disabled_reason", sa.Text(), nullable=True),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "model_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("component", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_payloads",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", "fetched_at"),
        postgresql_partition_by="RANGE (fetched_at)",
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("esco_uri", sa.Text(), nullable=True),
        sa.Column("o_net_code", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_name"),
    )
    op.create_table(
        "task_queue",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task_type", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("dedup_key", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("4"), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_task_queue_claim",
        "task_queue",
        [sa.literal_column("priority DESC"), "run_after"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(
        "ux_task_queue_dedup",
        "task_queue",
        ["dedup_key"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending','running')"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("locale", sa.Text(), server_default=sa.text("'en'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "company_aliases",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("lang", sa.Text(), server_default=sa.text("'en'"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias", "lang"),
    )
    op.create_table(
        "company_review_queue",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("observed_name", sa.Text(), nullable=False),
        sa.Column("observed_domain", sa.Text(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("suggested_company_id", sa.UUID(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("matched_alias", sa.Text(), nullable=True),
        sa.Column("occurrences", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["job_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suggested_company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("observed_name", "source_id"),
    )
    op.create_table(
        "consents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cv_documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("mime", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "sha256"),
    )
    op.create_table(
        "job_postings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_group_id", sa.UUID(), nullable=True),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("company_name_raw", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("title_normalized", sa.Text(), nullable=False),
        sa.Column("description_text", sa.Text(), nullable=False),
        sa.Column("locations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("remote_type", sa.Text(), nullable=True),
        sa.Column("employment_type", sa.Text(), nullable=True),
        sa.Column("seniority_level", sa.Text(), nullable=True),
        sa.Column("salary_min", sa.Numeric(), nullable=True),
        sa.Column("salary_max", sa.Numeric(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ats_platform", sa.Text(), nullable=True),
        sa.Column("ats_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("detection_method", sa.Text(), nullable=True),
        sa.Column("apply_url", sa.Text(), nullable=False),
        sa.Column("apply_url_method", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("url_status", sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content_simhash", sa.BigInteger(), nullable=True),
        sa.Column("language", sa.String(length=2), nullable=True),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_group_id"],
            ["job_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["job_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(
        "ix_job_postings_canonical_url", "job_postings", ["canonical_url"], unique=False
    )
    op.create_index(
        "ix_job_postings_company_title",
        "job_postings",
        ["company_id", "title_normalized"],
        unique=False,
    )
    op.create_index("ix_job_postings_group", "job_postings", ["job_group_id"], unique=False)
    op.create_index(
        "ix_job_postings_last_verified_open",
        "job_postings",
        ["last_verified_at"],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_index(
        "ix_job_postings_posted_at_open",
        "job_postings",
        [sa.literal_column("posted_at DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "skill_aliases",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("lang", sa.Text(), server_default=sa.text("'en'"), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias", "lang"),
    )
    op.create_table(
        "source_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("new_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("errors", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'running'"), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["job_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "unmapped_skills",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("lang", sa.Text(), server_default=sa.text("'en'"), nullable=False),
        sa.Column("occurrences", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_skill_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resolved_skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", "lang"),
    )
    op.create_table(
        "cv_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cv_document_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("parse_quality", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("parser_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cv_document_id"], ["cv_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_embeddings",
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=384), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["posting_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("posting_id"),
    )
    op.create_table(
        "job_requirements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("is_must_have", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=True),
        sa.Column("span", postgresql.INT4RANGE(), nullable=False),
        sa.ForeignKeyConstraint(["posting_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_job_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("event", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["posting_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("cv_version_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'applied'"), nullable=False),
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cv_version_id"],
            ["cv_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["job_postings.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "posting_id"),
    )
    op.create_table(
        "candidate_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("cv_version_id", sa.UUID(), nullable=False),
        sa.Column("years_experience", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("seniority_level", sa.Text(), nullable=True),
        sa.Column("locations", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("work_auth", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("languages", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("extraction_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cv_version_id"],
            ["cv_versions.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "application_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.Text(), nullable=True),
        sa.Column("to_status", sa.Text(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "eval_labels",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("grade", sa.SmallInteger(), nullable=False),
        sa.Column("labeler", sa.Text(), nullable=False),
        sa.Column(
            "labeled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("grade BETWEEN 0 AND 3", name="eval_labels_grade_check"),
        sa.ForeignKeyConstraint(
            ["posting_id"],
            ["job_postings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["candidate_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "posting_id", "labeler"),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("total_score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("percentile", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("gate_passed", sa.Boolean(), nullable=False),
        sa.Column("gate_failures", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("subscores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["posting_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["candidate_profiles.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "posting_id", "model_version"),
    )
    op.create_index(
        "ix_matches_user_score",
        "matches",
        ["user_id", sa.literal_column("total_score DESC")],
        unique=False,
        postgresql_where=sa.text("gate_passed"),
    )
    op.create_table(
        "profile_skills",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("proficiency", sa.Text(), nullable=True),
        sa.Column("evidence_span", postgresql.INT4RANGE(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["candidate_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match_evidence",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("requirement_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("cv_span", postgresql.INT4RANGE(), nullable=True),
        sa.Column("similarity", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["job_requirements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ── Indexes that no ORM metadata can express (§6.3) ──────────────
    op.execute(
        """
        CREATE INDEX job_fts_idx ON job_postings
          USING GIN (to_tsvector('simple', title || ' ' || description_text))
        """
    )
    # HNSW over halfvec: half precision halves index memory at negligible
    # recall cost, which is what keeps the index resident on a free-tier host.
    op.execute(
        """
        CREATE INDEX job_vec_idx ON job_embeddings
          USING hnsw (embedding halfvec_cosine_ops) WITH (m = 16, ef_construction = 64)
        """
    )
    op.execute(
        "CREATE INDEX company_alias_trgm_idx ON company_aliases USING GIN (alias gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX raw_payloads_source_external_idx ON raw_payloads (source_id, external_id)"
    )

    # ── raw_payloads partitions ──────────────────────────────────────
    # Monthly range partitions, pruned after 90 days (§6.4). The current month
    # and the next two are created here; `prune_raw` maintains the rolling
    # window thereafter. DEFAULT catches anything that would otherwise fail an
    # insert — an unpartitioned row is a bug, not a reason to lose the payload.
    op.execute(
        """
        DO $$
        DECLARE
            start_month date := date_trunc('month', now())::date;
            i int;
            from_date date;
            to_date date;
        BEGIN
            FOR i IN -1..2 LOOP
                from_date := (start_month + (i || ' month')::interval)::date;
                to_date := (start_month + ((i + 1) || ' month')::interval)::date;
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS raw_payloads_%s PARTITION OF raw_payloads '
                    'FOR VALUES FROM (%L) TO (%L)',
                    to_char(from_date, 'YYYYMM'), from_date, to_date
                );
            END LOOP;
        END $$;
        """
    )
    op.execute("CREATE TABLE IF NOT EXISTS raw_payloads_default PARTITION OF raw_payloads DEFAULT")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS job_fts_idx")
    op.execute("DROP INDEX IF EXISTS job_vec_idx")
    op.execute("DROP INDEX IF EXISTS company_alias_trgm_idx")
    op.execute("DROP INDEX IF EXISTS raw_payloads_source_external_idx")
    op.drop_table("match_evidence")
    op.drop_table("profile_skills")
    op.drop_index(
        "ix_matches_user_score", table_name="matches", postgresql_where=sa.text("gate_passed")
    )
    op.drop_table("matches")
    op.drop_table("eval_labels")
    op.drop_table("application_events")
    op.drop_table("candidate_profiles")
    op.drop_table("applications")
    op.drop_table("user_job_events")
    op.drop_table("job_requirements")
    op.drop_table("job_embeddings")
    op.drop_table("cv_versions")
    op.drop_table("unmapped_skills")
    op.drop_table("source_runs")
    op.drop_table("skill_aliases")
    op.drop_index(
        "ix_job_postings_posted_at_open",
        table_name="job_postings",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(
        "ix_job_postings_last_verified_open",
        table_name="job_postings",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index("ix_job_postings_group", table_name="job_postings")
    op.drop_index("ix_job_postings_company_title", table_name="job_postings")
    op.drop_index("ix_job_postings_canonical_url", table_name="job_postings")
    op.drop_table("job_postings")
    op.drop_table("cv_documents")
    op.drop_table("consents")
    op.drop_table("company_review_queue")
    op.drop_table("company_aliases")
    op.drop_table("users")
    op.drop_index(
        "ux_task_queue_dedup",
        table_name="task_queue",
        postgresql_where=sa.text("status IN ('pending','running')"),
    )
    op.drop_index(
        "ix_task_queue_claim",
        table_name="task_queue",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("task_queue")
    op.drop_table("skills")
    op.drop_table("raw_payloads")
    op.drop_table("model_runs")
    op.drop_table("job_sources")
    op.drop_table("job_groups")
    op.drop_table("companies")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
