"""phase 3: digest sends

Revision ID: ddb09d40b226
Revises: 182cea8a4fac
Create Date: 2026-09-09 17:15:50.548973+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (autogenerate emits halfvec columns)
import sqlalchemy as sa
from alembic import op

revision: str = "ddb09d40b226"
down_revision: str | None = "182cea8a4fac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "digest_sends",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("posting_id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.Text(), nullable=True),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["posting_id"], ["job_postings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "posting_id"),
    )
    op.create_index(
        "ix_digest_sends_user_sent", "digest_sends", ["user_id", "sent_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_digest_sends_user_sent", table_name="digest_sends")
    op.drop_table("digest_sends")
    # ### end Alembic commands ###
