"""Phase 1 — sentence-level embeddings and match explanations (§7.2, §8.5)

Revision ID: e68d36ca838f
Revises: bd890a7822e8
Create Date: 2026-09-09 11:54:57.152548+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e68d36ca838f"
down_revision: str | None = "bd890a7822e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_bullets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("span", postgresql.INT4RANGE(), nullable=True),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=384), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["candidate_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_profile_bullets_profile", "profile_bullets", ["profile_id"], unique=False)
    op.create_index(
        "profile_bullet_vec_idx",
        "profile_bullets",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.create_table(
        "profile_embeddings",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.halfvec.HALFVEC(dim=384), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["candidate_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    op.create_index("ix_job_requirements_posting", "job_requirements", ["posting_id"], unique=False)
    op.add_column("matches", sa.Column("explanation", sa.Text(), nullable=True))
    op.add_column("matches", sa.Column("gaps", sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "gaps")
    op.drop_column("matches", "explanation")
    op.drop_index("ix_job_requirements_posting", table_name="job_requirements")
    op.drop_table("profile_embeddings")
    op.drop_index(
        "profile_bullet_vec_idx",
        table_name="profile_bullets",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.drop_index("ix_profile_bullets_profile", table_name="profile_bullets")
    op.drop_table("profile_bullets")
    # ### end Alembic commands ###
