"""one row per skill per profile

Revision ID: eb65c240892f
Revises: 69741dd4c4fc
Create Date: 2026-09-14 12:19:19.653099+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401  (autogenerate emits halfvec columns)
from alembic import op

revision: str = "eb65c240892f"
down_revision: str | None = "69741dd4c4fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Existing duplicates have to go before the constraint can be added. Keep
    # the best-evidenced row per (profile, skill) rather than an arbitrary one:
    # a mention carrying a real span and a year count is worth more than a bare
    # one, and that is the row the evidence view should cite.
    op.execute(
        """
        DELETE FROM profile_skills ps
         WHERE ps.id NOT IN (
             SELECT DISTINCT ON (profile_id, skill_id) id
               FROM profile_skills
              ORDER BY profile_id, skill_id,
                       (evidence_span IS NOT NULL AND evidence_span <> '[0,0)') DESC,
                       (years IS NOT NULL) DESC,
                       (proficiency IS NOT NULL) DESC,
                       id
         )
        """
    )
    op.create_unique_constraint(
        "uq_profile_skills_profile_skill", "profile_skills", ["profile_id", "skill_id"]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_profile_skills_profile_skill", "profile_skills", type_="unique")
    # ### end Alembic commands ###
