"""The five sub-scores (§8.4).

Each is a number in [0, 1] with a stated meaning, computed by code that can be
read. No model produces any of them, and each carries the evidence that
produced it — which is what makes the explanation citable rather than
plausible-sounding.

The rejected alternative (§8.1) is one cosine between a whole CV and a whole
job description. It is one line of code, it compresses every candidate into the
0.60–0.85 band, it cannot see a hard disqualifier, and it cannot be explained.
"""

from __future__ import annotations

import math
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from datetime import datetime, timedelta

from app.domain.models import SENIORITY_ORDER, PostingRequirement, Seniority

MUST_HAVE_WEIGHT = 3.0
"""Must-haves count triple. A nice-to-have is a preference; a must-have is a filter."""


@dataclass(frozen=True, slots=True)
class SkillCoverage:
    score: float
    matched: tuple[str, ...]
    missing: tuple[str, ...]
    missing_must_haves: tuple[str, ...]
    matched_count: int
    total_count: int

    @property
    def fraction(self) -> str:
        """What the user is shown: an explicit matched/total, not a percentage."""
        return f"{self.matched_count}/{self.total_count}"


def skill_coverage(
    candidate_skills: frozenset[str],
    requirements: Sequence[PostingRequirement],
    *,
    fuzzy_match: Callable[[str, frozenset[str]], str | None] | None = None,
) -> SkillCoverage:
    """Weighted share of the posting's skill requirements the candidate holds.

    Matching is exact through the canonical taxonomy — both sides were resolved
    to canonical names before they got here, which is what makes an exact match
    meaningful. `fuzzy_match` supplies the §8.4 cosine fallback for names the
    taxonomy has not yet related.
    """
    skill_requirements = [
        requirement
        for requirement in requirements
        if requirement.kind == "skill" and requirement.skill
    ]
    if not skill_requirements:
        # Nothing to cover. Neutral rather than zero: a posting that lists no
        # skills should not sink to the bottom of every candidate's list.
        return SkillCoverage(1.0, (), (), (), 0, 0)

    matched: list[str] = []
    missing: list[str] = []
    missing_must_haves: list[str] = []
    earned = 0.0
    available = 0.0

    for requirement in skill_requirements:
        skill = requirement.skill or ""
        weight = MUST_HAVE_WEIGHT if requirement.is_must_have else 1.0
        available += weight

        hit = skill in candidate_skills
        if not hit and fuzzy_match is not None:
            hit = fuzzy_match(skill, candidate_skills) is not None

        if hit:
            matched.append(skill)
            earned += weight
        else:
            missing.append(skill)
            if requirement.is_must_have:
                missing_must_haves.append(skill)

    return SkillCoverage(
        score=round(earned / available, 4) if available else 1.0,
        matched=tuple(matched),
        missing=tuple(missing),
        missing_must_haves=tuple(missing_must_haves),
        matched_count=len(matched),
        total_count=len(skill_requirements),
    )


@dataclass(frozen=True, slots=True)
class RequirementEvidence:
    requirement: str
    similarity: float
    best_bullet: str | None
    status: str
    """met | partial | missing"""


@dataclass(frozen=True, slots=True)
class RequirementAlignment:
    score: float
    evidence: tuple[RequirementEvidence, ...] = field(default=())


MET_THRESHOLD = 0.72
PARTIAL_THRESHOLD = 0.55
"""Provisional. These decide whether a requirement reads as met, partial or
missing, and they are the one part of the scorer that has not been measured:
they are calibrated for `multilingual-e5-small`, whose sentence similarities run
high, and are meaningless for the deterministic development backend. Phase 2's
golden set (§9.1) is what turns them from a guess into a number — until then, a
requirement marked `missing` in development may only mean the fallback embedder
cannot see the relationship."""


def requirement_alignment(
    requirements: Sequence[PostingRequirement],
    bullets: Sequence[str],
    similarity: Callable[[str, str], float],
) -> RequirementAlignment:
    """For each requirement, the best-matching CV bullet; the mean of those maxima.

    The by-product is the point: the bullet that scored highest for a
    requirement *is* the evidence shown to the user, so the explanation is
    generated by the same computation as the score rather than narrated
    afterwards by a model.
    """
    if not requirements:
        return RequirementAlignment(1.0, ())
    if not bullets:
        return RequirementAlignment(
            0.0,
            tuple(
                RequirementEvidence(requirement.text, 0.0, None, "missing")
                for requirement in requirements
            ),
        )

    evidence: list[RequirementEvidence] = []
    total = 0.0
    for requirement in requirements:
        best_score = 0.0
        best_bullet: str | None = None
        for bullet in bullets:
            score = similarity(requirement.text, bullet)
            if score > best_score:
                best_score, best_bullet = score, bullet
        total += best_score
        evidence.append(
            RequirementEvidence(
                requirement=requirement.text,
                similarity=round(best_score, 3),
                best_bullet=best_bullet if best_score >= PARTIAL_THRESHOLD else None,
                status=(
                    "met"
                    if best_score >= MET_THRESHOLD
                    else "partial"
                    if best_score >= PARTIAL_THRESHOLD
                    else "missing"
                ),
            )
        )

    return RequirementAlignment(round(total / len(requirements), 4), tuple(evidence))


UNDER_QUALIFIED_PENALTY = 0.30
OVER_QUALIFIED_PENALTY = 0.15
"""Under-qualification is penalised about twice as heavily as over-qualification
(§8.4) — a stretch upward is usually a rejection, a step down is usually a
choice — but neither is free."""


def seniority_fit(candidate: Seniority | None, posting: Seniority | None) -> tuple[float, str]:
    """Ordinal distance over the seniority ladder, penalised asymmetrically."""
    if candidate is None or posting is None:
        # Neutral, not zero: an unstated level is missing information, and §8.3
        # already refuses to invent one.
        return 0.70, "level not stated on both sides"

    order = {level: index for index, level in enumerate(SENIORITY_ORDER)}
    distance = order[posting] - order[candidate]

    if distance == 0:
        return 1.0, "level matches"
    if distance > 0:
        score = max(0.0, 1.0 - UNDER_QUALIFIED_PENALTY * distance)
        return round(score, 4), f"{distance} level(s) above the candidate"
    score = max(0.0, 1.0 - OVER_QUALIFIED_PENALTY * abs(distance))
    return round(score, 4), f"{abs(distance)} level(s) below the candidate"


def normalize_semantic(raw_score: float, pool: Sequence[float]) -> float:
    """Min-max the cross-encoder score within this candidate's own pool (§8.4).

    Cross-encoder outputs are unbounded logits whose absolute value means
    nothing across queries. Normalising within the pool is what makes the
    sub-score comparable between postings for one candidate — and it is why the
    presentation layer talks in percentiles rather than absolutes.
    """
    if not pool:
        return 0.5
    lowest, highest = min(pool), max(pool)
    if math.isclose(highest, lowest):
        return 0.5
    return round((raw_score - lowest) / (highest - lowest), 4)


def freshness(posted_at: datetime | None, *, now: datetime, half_life_days: float = 7.0) -> float:
    """Exponential decay with a seven-day half-life (§8.4).

    A posting with no date scores as if it were one half-life old: unknown
    freshness is not fresh, and it is not stale either.
    """
    if posted_at is None:
        return 0.5
    age = now - posted_at
    if age < timedelta(0):
        return 1.0
    days = age.total_seconds() / 86400.0
    return round(float(0.5 ** (days / half_life_days)), 4)
